### ISSUE TITLE
Can't login to curiosity stream

### ISSUE THREAD

**Issue by blemasle** [matthuisman/plugin.video.curiositystream#3]
Hello there,

I was glad to discover that a Kodi plugin was available for kodi. Sadly, after many tries, I cannot login to my curiositystream account. Every single time, the plugin told me that my credentials were incorrect.

I already tried to reduce the set (only alphanumeric digits) and number of characters (down to 15) used for the password, but it didn't change a thing. Is there anything I can do to find the root cause of this error ?

Cheers,
Bertrand

**Comment by matthuisman** [comment]
I have no such issue.
Can you try setting it to something very simply (eg. 2 letters and 2 numbers) and test.

**Comment by blemasle** [comment]
Sorry for the delay. I'll have another look at it as soon as possible.

**Comment by blemasle** [comment]
Indeed it worked with a reduced number of characters. The amount of characters is the issue, not the set. I tried to use a long sentence as a password and it did not worked.

After many tries, I'm not sure if the problem comes from a typo error or from the plugin itself :)

**Comment by matthuisman** [comment]
I just tried this password (71 characters)

^oORqMSc#uDmQ%v#NcY57YfOpj&!97sjxJ*CNOvioQ#j8nR77bEXEPA7wap@$f%G&KPPaH&

and that worked.

So I suggest it's a typo error O instead of 0 or something like that.

**Comment by blemasle** [comment]
I did try many passwords before opening the issue but yeah, probably a typo, or a keyboard layout issue (I never use one on my Kodi setup). Sorry for the inconvenience :)
